[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://react-switch-game.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200